// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skqjlrryaravvqdphkov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrcWpscnJ5YXJhdnZxZHBoa292Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjM2MTMsImV4cCI6MjA2OTAzOTYxM30.LCG_Gp4PB5W-WZYNGgfrdWD4P0tR93eFOyUZm_pBCx4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});